"""
plot_diagnostics.py  (v2 – polished, config-driven)
====================================================
All user-facing settings live in config.py.
Do NOT edit this file – edit config.py instead.

Features:
  • Per-subplot colorbar with labelled VM-strain scale
  • Cmap Min / Cmap Max sliders for live colour-range adjustment
  • Dark-themed control strip with no widget overlap
  • x-axis label only on the bottom subplot
  • Status bar: cursor readout (left)  |  search result (right)
  • Keyboard shortcut  C  =  clear all markers
  • Safe TextBox input (no crash on non-numeric text)
  • axes kept as plain list throughout (fixes .index() on ndarray)
  • Pixel-coord clamped in on_move (no IndexError at image edges)
  • Guard in update_diff_search when delta_cols >= image width
  • plt.switch_backend called once before the loop
"""

from __future__ import annotations
import re, warnings
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.ndimage import gaussian_filter
from skimage.registration import optical_flow_ilk
from mpl_toolkits.axes_grid1 import make_axes_locatable

import matplotlib.pyplot as plt
from matplotlib.widgets import TextBox, Slider, Button

import config as cfg

warnings.filterwarnings("ignore")

# ── Pull settings from config ─────────────────────────────────────────────
IMAGE_DIR      = cfg.IMAGE_DIR
OUTPUT_DIR     = cfg.OUTPUT_DIR
PIXEL_SIZE_MM  = cfg.PIXEL_SIZE_MM
MIDLINE_ROW    = cfg.MIDLINE_ROW
SPECIMEN_ROI_Y = cfg.SPECIMEN_ROI_Y
SPECIMEN_ROI_X = cfg.SPECIMEN_ROI_X
ILK_RADIUS     = cfg.ILK_RADIUS
ILK_WARPS      = cfg.ILK_WARPS
DS_DISP        = cfg.DS_DISP
SS_DISP        = cfg.SS_DISP
Y_SEARCH_MIN   = cfg.Y_SEARCH_MIN
Y_SEARCH_MAX   = cfg.Y_SEARCH_MAX
VMIN_DEFAULT   = cfg.VMIN_DEFAULT
VMAX_DEFAULT   = cfg.VMAX_DEFAULT
BATCH_SIZE     = cfg.BATCH_SIZE

dic_cache: dict = {}


# ══════════════════════════════════════════════════════════════════════
#  DIC ENGINE
# ══════════════════════════════════════════════════════════════════════

def _frame_num(p: Path) -> int:
    nums = re.findall(r"\d+", p.stem)
    return max(int(n) for n in nums) if nums else 0


def load_files():
    files = sorted(
        [p for p in IMAGE_DIR.iterdir() if p.suffix.lower() in (".tif", ".tiff")],
        key=_frame_num,
    )
    if not files:
        raise FileNotFoundError(
            f"No .tif/.tiff files found in:\n  {IMAGE_DIR}\n"
            "Please update IMAGE_DIR in config.py"
        )
    imgs = {i: np.array(Image.open(p)) for i, p in enumerate(files)}
    for k in imgs:
        if imgs[k].ndim == 3:
            imgs[k] = imgs[k][..., 0]
    return files, imgs


def get_cached_fields(ref_idx: int, def_idx: int, images: dict) -> np.ndarray:
    key = (ref_idx, def_idx)
    if key in dic_cache:
        return dic_cache[key]
    r0, r1 = SPECIMEN_ROI_Y
    c0, c1 = SPECIMEN_ROI_X
    ref_c = images[ref_idx][r0:r1, c0:c1].astype(float) / 255.0
    def_c = images[def_idx][r0:r1, c0:c1].astype(float) / 255.0
    v_px, u_px = optical_flow_ilk(ref_c, def_c, radius=ILK_RADIUS, num_warp=ILK_WARPS)
    ps  = PIXEL_SIZE_MM
    u_c = gaussian_filter(u_px, DS_DISP) * ps
    v_c = gaussian_filter(v_px, DS_DISP) * ps
    ex  = gaussian_filter(np.gradient(u_c, ps, axis=1), SS_DISP)
    ey  = gaussian_filter(np.gradient(v_c, ps, axis=0), SS_DISP)
    exy = gaussian_filter(
        0.5 * (np.gradient(u_c, ps, axis=0) + np.gradient(v_c, ps, axis=1)), SS_DISP
    )
    vm_c = np.sqrt(ex**2 - ex * ey + ey**2 + 3 * exy**2) * 100.0
    dic_cache[key] = vm_c
    return vm_c


def _extent() -> tuple[float, float, float, float]:
    """(left, right, bottom, top) in mm relative to midline."""
    r0, r1 = SPECIMEN_ROI_Y
    c0, c1 = SPECIMEN_ROI_X
    return (
        c0 * PIXEL_SIZE_MM,
        c1 * PIXEL_SIZE_MM,
        -(r1 - MIDLINE_ROW) * PIXEL_SIZE_MM,
        -(r0 - MIDLINE_ROW) * PIXEL_SIZE_MM,
    )


# ══════════════════════════════════════════════════════════════════════
#  HELPERS
# ══════════════════════════════════════════════════════════════════════

def _safe_float(s: str) -> float | None:
    try:
        return float(s)
    except (ValueError, TypeError):
        return None


def _style_slider(sld: Slider) -> None:
    sld.label.set_color("white")
    sld.valtext.set_color("white")


def _style_textbox(tb: TextBox) -> None:
    tb.label.set_color("white")
    try:
        tb.text_disp.set_color("white")
    except AttributeError:
        pass  # older matplotlib versions


# ══════════════════════════════════════════════════════════════════════
#  INTERACTIVE INSPECTOR
# ══════════════════════════════════════════════════════════════════════

def build_interactive_inspector(
    files: list,
    images: dict,
    batch_indices: list[int],
    batch_label: str,
) -> None:
    ref_idx = 0
    ext = _extent()
    n   = len(batch_indices)

    # ── Figure ──────────────────────────────────────────────────────
    plt.ion()
    fig, _axes = plt.subplots(n, 1, figsize=(18, 4 * n + 3), sharex=True)
    axes: list = [_axes] if n == 1 else list(_axes)

    fig.patch.set_facecolor("#1a1a2e")
    fig.canvas.manager.set_window_title(f"ENF Inspector – {batch_label}")
    fig.suptitle(
        f"ENF Crack Diagnostics  ·  {batch_label}  ·  Reference: Frame 0",
        fontsize=13, fontweight="bold", color="white", y=0.975,
    )

    # ── Subplots ────────────────────────────────────────────────────
    strain_data:  list[np.ndarray] = []
    im_handles:   list             = []
    scatter_plots                  = []
    diff_markers                   = []

    for i, (ax, key) in enumerate(zip(axes, batch_indices)):
        vm_crop = get_cached_fields(ref_idx, key, images)
        strain_data.append(vm_crop)

        ax.set_facecolor("#0d0d1a")
        im = ax.imshow(
            vm_crop, origin="upper", extent=ext,
            cmap="jet", vmin=VMIN_DEFAULT, vmax=VMAX_DEFAULT, aspect="equal",
        )
        im_handles.append(im)

        # Per-subplot colorbar
        divider = make_axes_locatable(ax)
        cax = divider.append_axes("right", size="1.8%", pad=0.07)
        cb  = fig.colorbar(im, cax=cax)
        cb.set_label("VM Strain [%]", fontsize=8, color="white")
        cb.ax.yaxis.set_tick_params(color="white", labelcolor="white", labelsize=7)
        cb.outline.set_edgecolor("#555")

        ax.set_title(
            f"Frame {_frame_num(files[key])}  (vs Ref 0)",
            fontsize=10, fontweight="bold", color="white", pad=4,
        )
        ax.set_ylabel("y [mm]", fontsize=9, color="white")
        ax.tick_params(colors="white", labelsize=8)
        for spine in ax.spines.values():
            spine.set_edgecolor("#444")

        if i == n - 1:
            ax.set_xlabel("x [mm]", fontsize=9, color="white")

        sc = ax.scatter([], [], s=16, color="red", zorder=6, alpha=0.75, linewidths=0)
        scatter_plots.append(sc)

        pt1,  = ax.plot([], [], "o", color="cyan",   ms=9,  visible=False, zorder=7)
        pt2,  = ax.plot([], [], "o", color="yellow", ms=9,  visible=False, zorder=7)
        conn, = ax.plot([], [], "-", color="white",  lw=1.8, visible=False, zorder=7)
        diff_markers.append((pt1, pt2, conn))

    # ── Status bar ─────────────────────────────────────────────────
    _bar_kw     = dict(fontsize=9, family="monospace")
    _bbox_style = dict(alpha=0.85, boxstyle="round,pad=0.35")

    coord_text = fig.text(
        0.02, 0.153,
        "Cursor →  X: ---  |  Y: ---  |  VM: --- %",
        color="#88ff88",
        bbox=dict(facecolor="#0d1f0d", edgecolor="#2a5a2a", **_bbox_style),
        **_bar_kw,
    )
    result_text = fig.text(
        0.46, 0.153,
        "Result: awaiting input",
        color="#66ccff",
        bbox=dict(facecolor="#0d1a2e", edgecolor="#2a4a7a", **_bbox_style),
        **_bar_kw,
    )
# ── Control strip – Row 1: Strain threshold + Cmap range ────────
    _ctrl_bg = "#1e1e30"

    # VM Threshold
    ax_s_box = fig.add_axes([0.02, 0.095, 0.045, 0.034], facecolor=_ctrl_bg)
    txt_s = TextBox(ax_s_box, "VM ≥ ", initial="1.0", color=_ctrl_bg, hovercolor="#2e2e44")
    _style_textbox(txt_s)

    ax_s_sld = fig.add_axes([0.15, 0.095, 0.18, 0.034], facecolor=_ctrl_bg)
    sld_s = Slider(ax_s_sld, "Strain threshold [%]", 0.0, 15.0,
                   valinit=1.0, valstep=0.1, color="#3a5aaa")
    _style_slider(sld_s)

    # Colormap Range (These were missing!)
    ax_vmin = fig.add_axes([0.43, 0.095, 0.15, 0.034], facecolor=_ctrl_bg)
    sld_vmin = Slider(ax_vmin, "Cmap Min", 0.0, 10.0,
                      valinit=VMIN_DEFAULT, valstep=0.5, color="#556633")
    _style_slider(sld_vmin)

    ax_vmax = fig.add_axes([0.65, 0.095, 0.15, 0.034], facecolor=_ctrl_bg)
    sld_vmax = Slider(ax_vmax, "Cmap Max", 1.0, 30.0,
                      valinit=VMAX_DEFAULT, valstep=0.5, color="#aa4422")
    _style_slider(sld_vmax)

    # ── Control strip – Row 2: Abs-diff probe + Clear ───────────────
    # Δx Probe
    ax_d_box = fig.add_axes([0.02, 0.045, 0.045, 0.034], facecolor=_ctrl_bg)
    txt_d = TextBox(ax_d_box, "Δx  ", initial="5.0", color=_ctrl_bg, hovercolor="#2e2e44")
    _style_textbox(txt_d)

    ax_d_sld = fig.add_axes([0.15, 0.045, 0.18, 0.034], facecolor=_ctrl_bg)
    sld_d = Slider(ax_d_sld, "Abs-diff probe gap [mm]", 0.0, 10.0,
                   valinit=5.0, valstep=0.1, color="#3a5aaa")
    _style_slider(sld_d)

    # Clear Button
    ax_clear = fig.add_axes([0.855, 0.038, 0.115, 0.072])
    btn_clear = Button(ax_clear, "CLEAR ALL\n[press  C]", color="#7a1a1a", hovercolor="#cc2222")
    btn_clear.label.set_color("white")
    btn_clear.label.set_fontsize(9)
    btn_clear.label.set_fontweight("bold")

    fig.text(
        0.50, 0.005,
        "Hover plots for pixel readout  ·  TextBoxes accept typed values  ·  C = clear markers",
        fontsize=7.5, color="#666680", ha="center",
    )

    # ──────────────────────────────────────────────────────────────
    #  Callbacks
    # ──────────────────────────────────────────────────────────────

    def update_strain_search(val: float) -> None:
        target = float(val)
        for i, (data, _ax) in enumerate(zip(strain_data, axes)):
            rows, cols = np.where(data >= target)
            x_pts = ext[0] + cols * PIXEL_SIZE_MM
            y_pts = ext[3] - rows * PIXEL_SIZE_MM
            mask  = (y_pts >= Y_SEARCH_MIN) & (y_pts <= Y_SEARCH_MAX)
            scatter_plots[i].set_offsets(
                np.column_stack([x_pts[mask], y_pts[mask]])
                if np.any(mask) else np.empty((0, 2))
            )
        fig.canvas.draw_idle()

    def update_diff_search(val: float) -> None:
        delta_mm   = float(val)
        delta_cols = max(1, int(round(delta_mm / PIXEL_SIZE_MM)))
        best_diff  = -1.0
        best_info  = ""

        for i, (data, _ax) in enumerate(zip(strain_data, axes)):
            pt1, pt2, conn = diff_markers[i]
            r_start = max(0,             int((ext[3] - Y_SEARCH_MAX) / PIXEL_SIZE_MM))
            r_end   = min(data.shape[0], int((ext[3] - Y_SEARCH_MIN) / PIXEL_SIZE_MM))
            sub = data[r_start:r_end, :]

            if sub.shape[1] <= delta_cols or sub.size == 0:
                for art in (pt1, pt2, conn): art.set_visible(False)
                continue

            abs_diff = np.abs(sub[:, :-delta_cols] - sub[:, delta_cols:])
            if abs_diff.max() == 0:
                for art in (pt1, pt2, conn): art.set_visible(False)
                continue

            ir, ic = np.unravel_index(np.argmax(abs_diff), abs_diff.shape)
            r_best = ir + r_start
            x1  = ext[0] + ic * PIXEL_SIZE_MM
            x2  = ext[0] + (ic + delta_cols) * PIXEL_SIZE_MM
            y_m = ext[3] - r_best * PIXEL_SIZE_MM

            pt1.set_data([x1], [y_m]);           pt1.set_visible(True)
            pt2.set_data([x2], [y_m]);           pt2.set_visible(True)
            conn.set_data([x1, x2], [y_m, y_m]); conn.set_visible(True)

            if abs_diff.max() > best_diff:
                best_diff = abs_diff.max()
                best_info = (
                    f"MAX |ΔVM|: {best_diff:.3f}%  ·  "
                    f"X = {x1:.2f} → {x2:.2f} mm  ·  "
                    f"Y = {y_m:.2f} mm  ·  "
                    f"Frame {_frame_num(files[batch_indices[i]])}"
                )

        result_text.set_text(best_info if best_diff > 0 else "No valid points found")
        fig.canvas.draw_idle()

    def update_clim(val: float) -> None:
        vmin, vmax = sld_vmin.val, sld_vmax.val
        if vmin >= vmax:
            return
        for im in im_handles:
            im.set_clim(vmin, vmax)
        fig.canvas.draw_idle()

    def clear_all(event=None) -> None:
        for sc in scatter_plots:
            sc.set_offsets(np.empty((0, 2)))
        for pt1, pt2, conn in diff_markers:
            for art in (pt1, pt2, conn):
                art.set_visible(False)
        result_text.set_text("Result: cleared")
        fig.canvas.draw_idle()

    def on_key(event) -> None:
        if event.key and event.key.lower() == "c":
            clear_all()

    def on_move(event) -> None:
        if event.inaxes not in axes or event.xdata is None:
            return
        idx  = axes.index(event.inaxes)
        data = strain_data[idx]
        col  = int(np.clip((event.xdata - ext[0]) / PIXEL_SIZE_MM, 0, data.shape[1] - 1))
        row  = int(np.clip((ext[3] - event.ydata) / PIXEL_SIZE_MM, 0, data.shape[0] - 1))
        val  = data[row, col]
        coord_text.set_text(
            f"Cursor →  X: {event.xdata:7.2f}  |  Y: {event.ydata:6.2f}  |  VM: {val:6.3f} %"
        )
        fig.canvas.draw_idle()

    # ── Wire up ────────────────────────────────────────────────────
    def _on_s_submit(v):
        f = _safe_float(v)
        if f is not None: sld_s.set_val(np.clip(f, 0.0, 15.0))

    def _on_d_submit(v):
        f = _safe_float(v)
        if f is not None: sld_d.set_val(np.clip(f, 0.0, 10.0))

    txt_s.on_submit(_on_s_submit)
    sld_s.on_changed(update_strain_search)
    txt_d.on_submit(_on_d_submit)
    sld_d.on_changed(update_diff_search)
    sld_vmin.on_changed(update_clim)
    sld_vmax.on_changed(update_clim)
    btn_clear.on_clicked(clear_all)
    fig.canvas.mpl_connect("motion_notify_event", on_move)
    fig.canvas.mpl_connect("key_press_event",     on_key)

    plt.subplots_adjust(left=0.05, right=0.91, bottom=0.19, top=0.94, hspace=0.38)
    plt.show(block=True)


# ══════════════════════════════════════════════════════════════════════
#  MAIN SELECTOR
# ══════════════════════════════════════════════════════════════════════

def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    try:
        plt.switch_backend("TkAgg")
    except Exception:
        pass

    print("\nLoading images …  (this may take a moment on first run)")
    files, images = load_files()
    non_ref = [k for k in sorted(images) if k != 0]
    batches = [non_ref[i: i + BATCH_SIZE] for i in range(0, len(non_ref), BATCH_SIZE)]

    while True:
        print("\n" + "=" * 52)
        print("  ENF DIAGNOSTICS – BATCH SELECTOR")
        print("=" * 52)
        for i, b in enumerate(batches):
            frames = [_frame_num(files[f]) for f in b]
            print(f"  [{i:2d}]  Frames: {frames}")
        print("  [ Q]  Quit")

        choice = input("\nSelect batch index or Q: ").strip().upper()
        if choice == "Q":
            break
        if choice.isdigit() and int(choice) < len(batches):
            build_interactive_inspector(
                files, images,
                batches[int(choice)],
                f"Batch {int(choice) + 1}",
            )


if __name__ == "__main__":
    main()
